CREATE TABLE CARGO(
    idCargo INTEGER PRIMARY KEY NOT NULL,
    nombreCargo VARCHAR(40) NOT NULL
);

CREATE TABLE TIPO_PASAJERO(
    idTipoPasajero INTEGER PRIMARY KEY NOT NULL,
    descripcion VARCHAR(25) NOT NULL
);

CREATE TABLE PASAJERO(
    idPasajero INTEGER PRIMARY KEY NOT NULL,
    tipoDocumento VARCHAR(25) NOT NULL,
    documento VARCHAR(15) NOT NULL,
    nombres VARCHAR(40) NOT NULL,
    apellidos VARCHAR(45) NOT NULL,
    email VARCHAR(35),
    telefono NUMERIC NOT NULL,
    idTipoPasajero INTEGER FOREIGN KEY REFERENCES TIPO_PASAJERO (idTipoPasajero),
    idCargo INTEGER FOREIGN KEY REFERENCES CARGO (idCargo)
);

CREATE TABLE CIUDAD(
    idCiudad INTEGER PRIMARY KEY NOT NULL,
    nombreCiudad VARCHAR(50) NOT NULL
);

CREATE TABLE DEPARTMENTO(
    idDepartamento INTEGER PRIMARY KEY NOT NULL,
    nombreDepartamento VARCHAR(50) NOT NULL,
    idCiudad INTEGER FOREIGN KEY REFERENCES CIUDAD (idCiudad)
);

CREATE TABLE CODIGO_COMPANIA(
    idCodigoCompania INTEGER PRIMARY KEY NOT NULL,
    nombreCompania VARCHAR(50) NOT NULL
);

CREATE TABLE DESCUENTO(
    idDescuento INTEGER PRIMARY KEY NOT NULL,
    nombreDescuento VARCHAR(50) NOT NULL
);
CREATE TABLE PLANILLA_VUELO(
   idPlanillaVuelo INTEGER PRIMARY KEY NOT NULL, 
   nombrePlanilla VARCHAR(45) NOT NULL,
   idPasajero INTEGER FOREIGN KEY REFERENCES PASAJERO (idPasajero)
);

CREATE TABLE ESTADO_VUELO(
    idEstadoVuelo INTEGER PRIMARY KEY NOT NULL,
    descripcion VARCHAR(20) NOT NULL   
);

CREATE TABLE CLASE_VUELO(
    idClaseVuelo INTEGER PRIMARY KEY NOT NULL,
    nombreClase VARCHAR(20) NOT NULL
);

CREATE TABLE VUELO(
    idVuelo INTEGER PRIMARY KEY NOT NULL,
    nombreVuelo VARCHAR(50) NOT NULL,
    fechaInicio datetime NOT NULL,
    fechaFin datetime NOT NULL,
    costo NUMERIC NOT NULL,
    idClaseVuelo INTEGER FOREIGN KEY REFERENCES CLASE_VUELO (idClaseVuelo),
    idEstadoVuelo INTEGER FOREIGN KEY REFERENCES ESTADO_VUELO (idEstadoVuelo)
    idPlanillaVuelo INTEGER FOREIGN KEY REFERENCES PLANILLA_VUELO (idPlanillaVuelo),
    idCodigoCompania INTEGER FOREIGN KEY REFERENCES CODIGO_COMPANIA (idCodigoCompania),
    idDepartamento INTEGER FOREIGN KEY REFERENCES DEPARTMENTO (idDepartamento),
);


CREATE TABLE TIPO_TIQUETE(
    idTipoTiquete INTEGER PRIMARY KEY NOT NULL,
    descripcion VARCHAR(40) NOT NULL
);

CREATE TABLE TIQUETE(
    idTiquete INTEGER PRIMARY KEY NOT NULL,
    nombreTiquete VARCHAR(50) NOT NULL,
    idTipoTiquete INTEGER FOREIGN KEY REFERENCES TIPO_TIQUETE (idTipoTiquete),
    idDescuento INTEGER FOREIGN KEY REFERENCES DESCUENTO (idDescuento),
    idVuelo INTEGER FOREIGN KEY REFERENCES VUELO (idVuelo),
    idPasajero INTEGER FOREIGN KEY REFERENCES PASAJERO (idPasajero)
);

---CONSTRAINT